{{- range $key, $value := .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $value.name }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{- $value.file_name | nindent 2}}: |
    {{- $value.content | nindent 4}}
---
{{- end}}
{{- if gt len(.Values.sites) 0}}
{{- range $ks, $vs := .Values.sites }}
  {{- if gt len($vs.configmaps) 0}}
    {{- range $kc, $vc := $vs.configmaps}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $vc.file_name }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{- $vc.file_name | nindent 2}}: |
    {{- $vc.content | nindent 4}}
---
    {{- end}}
  {{- end}}
{{- end}}
{{- end}}