apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3pvc.fullname" . }}
  labels:
  {{- include "s3pvc.labels" . | nindent 4 }}
data:
  S3_REGION: {{- .Values.secret.S3_BUCKET | b64enc |quote }}
  S3_BUCKET: {{- .Values.secret.S3_BUCKET | b64enc |quote }}
  S3_ENDPOINT: {{- .Values.secret.S3_ENDPOINT | b64enc |quote }}
  AWS_KEY: {{- .Values.secret.AWS_KEY | b64enc |quote }}
  AWS_SECRET_KEY: {{- .Values.secret.AWS_SECRET_KEY | b64enc |quote }}