apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3pvc.fullname" . }}-env
  labels:
  {{- include "s3pvc.labels" . | nindent 4 }}
data:
  S3_REGION: {{- .Values.env.S3_REGION | quote | nindent 4}}
  S3_BUCKET: {{- .Values.env.S3_BUCKET | quote | nindent 4}}
  S3_ENDPOINT: {{- .Values.env.S3_ENDPOINT | quote | nindent 4}}
  AWS_KEY: {{- .Values.env.AWS_KEY | quote | nindent 4}}
  AWS_SECRET_KEY: {{- .Values.env.AWS_SECRET_KEY | quote | nindent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3pvc.fullname" . }}-run
  labels:
  {{- include "s3pvc.labels" . | nindent 4 }}
data:
  run.sh: |
    #!/bin/sh
    set -e
    echo "$AWS_KEY:$AWS_SECRET_KEY" > passwd && chmod 600 passwd
    s3fs "$S3_BUCKET" "$MNT_POINT" -o passwd_file=passwd,use_path_request_style,allow_other,url=$S3_ENDPOINT
    mkdir -p /etc/lsyncd
    rm -rf /etc/lsyncd/lsyncd.conf
    touch /etc/lsyncd/lsyncd.conf
    mkdir -p /var/log/lsyncd
    touch /var/log/lsyncd/lsyncd.log
    cat <<EOT >> /etc/lsyncd/lsyncd.conf
    settings {
      logfile = "/var/log/lsyncd/lsyncd.log",
      statusFile = "/var/log/lsyncd/lsyncd.status",
      pidfile = "/var/run/lsyncd.pid",
      statusInterval = 1,
      nodaemon = true,
      insist = true
    }

    sync {
      default.rsync,
      source = "/var/s3fs",
      target = "/var/s3fs:shared",
      delete = 'running',
      delay = 0,
      rsync = {
        update = true,
        times = true,
        archive = true,
        compress = true,
        perms = false,
        acls = true,
        owner = false,
      }
    }

    sync {
      default.rsync,
      source = "/var/s3fs:shared",
      target = "/var/s3fs",
      delete = 'running',
      delay = 0,
      rsync = {
        update = true,
        times = true,
        archive = true,
        compress = true,
        perms = false,
        acls = true,
        owner = false,
      }
    }
    EOT
    /usr/bin/lsyncd /etc/lsyncd/lsyncd.conf && tail -f /dev/null