apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "s3pvc.fullname" . }}
  labels:
  {{- include "s3pvc.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
  {{- include "s3pvc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "s3pvc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "s3pvc.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['sh','-c','./run.sh']
          envFrom:
            - configMapRef:
                name: {{ include "s3pvc.fullname" . }}-env
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: runsh
              mountPath: /run.sh
              subPath: run.sh
              readOnly: false
      {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        - name: runsh
          configMap:
            name: {{ include "s3pvc.fullname" . }}-run
            defaultMode: 0777
      {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}