apiVersion: v1
appVersion: "1.0.1"
description: A Helm chart for Konga in Kubernetes
name: konga
version: 1.0.1
# helm package konga --destination repo && helm repo index repo --url https://clackken.github.io/clack_helm/repo
